[build]
  # Build command
  command = "npm run build"
  
  # Base directory (root of the project)
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Settings for Next.js runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 